name: "Deploy to Nuget"
on:
 push:
 tags:
   'v*'

env:
PROJECT_PATH: 'DeleteConfirmationModal.csproj'
PACKAGE_OUTPUT_DIRECTORY: ${{github.workspace}}\output
NUGET_SOURCE_URL: ''https://api.nh=uget.org/v3/index./json''
jobs:
  	depoly:
    name:'Deploy'
    runs-on: 'windows-latest'
    setps:
    - name: 'Ckeckou'
      uses: actions/checkout@v1
    -name: 'install dotnet'
     uses: actions/setup-dotnet@v1

    - name: 'Restore packages'
      run: dotnet restore ${{env.PROJECT_PATH}}

      - name: 'Build project'
      run: dotnet build  --no-rectore --configuration Release

      - name: 'Pack project'
      run: donet pack ${{env.PROJECT_PATH}} --no-restore --no-build --configuration Release --include-symbols --output ${{env.PACKAGE_OUTPUT_DIRECTORY}}

      - name: 'Push package'
       run: dotnet nuget push  ${{env.PACKAGE_OUTPUT_DIRECTORY}}\*.nupkg -k ${{secrets.nuget_api_key}} -s ${{env.NUGET_SOURCE_URL}}
      
      
