name: "Deploy to Nuget"
on: ["push"]

env:
  PROJECT_PATH: 'DeleteConfirmationModal.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{github.workspace}}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1

    - name: 'Restore packages'
      run: dotnet restore ${{env.PROJECT_PATH}}

    - name: 'Build project'
      run: dotnet build --no-restore --configuration Release

    - name: 'Pack project'
      run: dotnet pack ${{env.PROJECT_PATH}} --no-restore --no-build --configuration Release --include-symbols --output ${{env.PACKAGE_OUTPUT_DIRECTORY}}
    
   
